on:
  push:
    branches: [dev]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        wait-timeout-minutes: 5