on:
  push:
    branches: [dev]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        wait-timeout-minutes: 5